language: rust

sudo: false

rust:
  - nightly
  - beta
  - stable

script:
  - |
    set -e
    cd codegen
    cargo build --verbose --features with-syntex
    cargo test --verbose --features with-syntex
    cd ..
    set +e
